import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const font = Inter({
  weight: ['400', '500', '600', '700', '900'],
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: "Arjun Portfolio",
  description: "Generated by Arjun",
  icons: "/vercel.svg",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${font.className} antialiased bg-[#0d0d1f]`}
      >
        {children}
      </body>
    </html>
  );
}
